services:
  mcp-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-ai-agent
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Add any environment variables here if needed
      # - MCP_SERVER_URL=http://your-mcp-server:8000/mcp
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
